version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: faultforge-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: faultforge
    ports:
      - "5433:5432"
    volumes:
      - faultforge_pgdata:/var/lib/postgresql/data

volumes:
  faultforge_pgdata: